server:
  port: 8080

spring:
  #解决中文乱码
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.1.34:3306/ssr_test_20191207?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: mysql#JN99@dev
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      #druid recycle
      remove-abandoned: true
      remove-abandoned-timeout-millis: 300
      log-abandoned: true
  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  # 404交给异常处理器处理
  resources:
    add-mappings: false
  redis:
    host: 122.112.204.214
    database: 12
    port: 6379
    password: jnsaa@redis.master
  #JAP 配置
  jpa:
    show-sql: true
